name: APK-ny Mugt Döretmek

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Koduňyzy barlamak
      uses: actions/checkout@v4

    - name: Java JDK 17 gurnamak
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Android SDK sazlamak
      uses: android-actions/setup-android@v3

    - name: Node.js gurnamak (Häzirki zaman wersiýasy)
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cordova gurnamak
      run: npm install -g cordova

    - name: Android Platformasyny goşmak we APK Gurmak
      run: |
        cordova platform add android
        cordova build android --release --no-telemetry

    - name: APK Faýlyny Ýüklemek (Göçürip almak üçin)
      uses: actions/upload-artifact@v4
      with:
        name: MeniňAndroidProgrammam
        path: platforms/android/app/build/outputs/apk/release/*.apk
      
